version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
    environment:
      PIPENV_VENV_IN_PROJECT: true
    resource_class: small
    steps:
      - checkout
      - restore_cache:
         keys:
           - pip-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
           - pip-{{ .Branch }}-
           - pip-
      - run: pipenv sync
      - save_cache:
          key: pip-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      - run: pipenv run ./lint.sh
      - run: pipenv run ./test.sh
      - run: pipenv run ./build.sh
      - run: if [[ "${CIRCLE_BRANCH}" != "main" ]]; then circleci-agent step halt fi
      - run: pipenv run twine upload dist/*

workflows:
  default:
    jobs:
      - build
