in_format: |
  Prescribes how to load the files.
  Default is "text".
  To specify a different format for each file, separate with a comma.
  For example, "--in-format yaml,json" will load the first file as YAML and the
  second as JSON.
  If you specify multiple parsers then you must specify an "--out-format".
out_format: |
  Prescribes how to format the result.
  This is used only if "--in-format" is not "text".
  Default is the same format as "--in-format" if only one format was specified.
  For example, "--in-format json --out-format yaml" will parse the input files
  as JSON, but present the diff as YAML.
